package com.fndong.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class mainLayoutDesign extends VerticalLayout {
	protected CssLayout top_area;
	protected Label lblheader;
	protected HorizontalLayout sidebar_contain;
	protected CssLayout side_menu;
	protected Button btnMenu1;
	protected Button btnMenu2;
	protected Button btnMenu3;
	protected VerticalLayout content_area;
	protected Label lbl_paragraph;
	protected FormLayout form_layout;
	protected TextField txtname;
	protected TextField txtlastname;
	protected TextField txtEmail;
	protected Button btnSubmit;

	public mainLayoutDesign() {
		Design.read(this);
	}
}
